### ISSUE TITLE
healthcheck cannot be seperated of main thread limit

### ISSUE THREAD

**Issue by 42Atomys** [bigcommerce/gruf#173] opened 2022-10-04 13:13 UTC
## Please describe the issue

When use Gruf behind a health-checker (implementation of https://github.com/grpc/grpc/blob/master/doc/health-checking.md), all probe is behind the THREAD_LIMIT of Gruf. And we dont found any solution about reserving a thread to the health-check. In some case, we reach the THREAD_LIMIT due to request pressure and the health-check have the same behaviour as client requests.

## How to Reproduce

1. Set the limit if gruf thread limit to 5
2. Perform 5 long requests (3/4 seconds for example)
3. Perform a healthcheck 
4. Response with `code_exhausted` error

## What _should_ happen?

Have a solution to reserve a thread to health check or exlude a request to the code exhausted ? 

## Anything else we should know?

* gRPC version : 1.48.0
* Ruby version : 3.1.2
* Does it occur at certain traffic volumes, payload size, etc : When gruf server is saturated

**Comment by splittingred** [comment] 2022-10-04 15:56
Hi @42Atomys - this is intended behavior (and the expected from gRPC). A health check is intended to check the health of the running process (not check some other thing), and if your gRPC thread pool is exhausted, it is intended behavior for that health check to then fail (as the process is then not healthy). If you are running so hot that you have no bandwidth for health checks (which should resolve in sub 1-3ms), you should consider horizontally scaling the thread pool size (or # of processes you run), as you're likely just barely avoiding resource exhaustion anyway.

Hope that helps. Closing this issue as wontfix.

**Closed by splittingred** 2022-10-04 15:56 UTC
